name: CI

on:
  push:
    branches: [ main, dev ]
  pull_request:
    branches: [ main, dev ]

jobs:
  build-and-test:
    runs-on: ubuntu-latest
    steps:
      - name: Checka ut koden
        uses: actions/checkout@v4

      - name: Satt upp Java 17
        uses: actions/setup-java@v4
        with:
          distribution: 'temurin'
          java-version: '17'
          cache: maven

      - name: Installera Playwrights webblasare
        run: |
         mvn test-compile
         mvn exec:java -e "-Dexec.mainClass=com.microsoft.playwright.CLI" "-Dexec.args=install --with-deps chromium" "-Dexec.classpathScope=test"

      - name: Bygg och kor tester
        run: mvn clean verify

